// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: protos/memory_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Context       map[string]string      `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ttl           int64                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"` // Time to live in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveContextRequest) Reset() {
	*x = SaveContextRequest{}
	mi := &file_protos_memory_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveContextRequest) ProtoMessage() {}

func (x *SaveContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_memory_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveContextRequest.ProtoReflect.Descriptor instead.
func (*SaveContextRequest) Descriptor() ([]byte, []int) {
	return file_protos_memory_service_proto_rawDescGZIP(), []int{0}
}

func (x *SaveContextRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SaveContextRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *SaveContextRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type SaveContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveContextResponse) Reset() {
	*x = SaveContextResponse{}
	mi := &file_protos_memory_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveContextResponse) ProtoMessage() {}

func (x *SaveContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_memory_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveContextResponse.ProtoReflect.Descriptor instead.
func (*SaveContextResponse) Descriptor() ([]byte, []int) {
	return file_protos_memory_service_proto_rawDescGZIP(), []int{1}
}

func (x *SaveContextResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveContextResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Keys          []string               `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"` // Optional: specific keys to retrieve
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContextRequest) Reset() {
	*x = GetContextRequest{}
	mi := &file_protos_memory_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContextRequest) ProtoMessage() {}

func (x *GetContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_memory_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContextRequest.ProtoReflect.Descriptor instead.
func (*GetContextRequest) Descriptor() ([]byte, []int) {
	return file_protos_memory_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetContextRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetContextRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type GetContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       map[string]string      `protobuf:"bytes,1,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContextResponse) Reset() {
	*x = GetContextResponse{}
	mi := &file_protos_memory_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContextResponse) ProtoMessage() {}

func (x *GetContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_memory_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContextResponse.ProtoReflect.Descriptor instead.
func (*GetContextResponse) Descriptor() ([]byte, []int) {
	return file_protos_memory_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetContextResponse) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetContextResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetContextResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Keys          []string               `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"` // Optional: specific keys to delete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContextRequest) Reset() {
	*x = DeleteContextRequest{}
	mi := &file_protos_memory_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContextRequest) ProtoMessage() {}

func (x *DeleteContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_memory_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContextRequest.ProtoReflect.Descriptor instead.
func (*DeleteContextRequest) Descriptor() ([]byte, []int) {
	return file_protos_memory_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteContextRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteContextRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type DeleteContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContextResponse) Reset() {
	*x = DeleteContextResponse{}
	mi := &file_protos_memory_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContextResponse) ProtoMessage() {}

func (x *DeleteContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_memory_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContextResponse.ProtoReflect.Descriptor instead.
func (*DeleteContextResponse) Descriptor() ([]byte, []int) {
	return file_protos_memory_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteContextResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteContextResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Context       map[string]string      `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ttl           int64                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"` // Optional: new TTL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContextRequest) Reset() {
	*x = UpdateContextRequest{}
	mi := &file_protos_memory_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContextRequest) ProtoMessage() {}

func (x *UpdateContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_memory_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContextRequest.ProtoReflect.Descriptor instead.
func (*UpdateContextRequest) Descriptor() ([]byte, []int) {
	return file_protos_memory_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateContextRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateContextRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UpdateContextRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type UpdateContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContextResponse) Reset() {
	*x = UpdateContextResponse{}
	mi := &file_protos_memory_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContextResponse) ProtoMessage() {}

func (x *UpdateContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_memory_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContextResponse.ProtoReflect.Descriptor instead.
func (*UpdateContextResponse) Descriptor() ([]byte, []int) {
	return file_protos_memory_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateContextResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateContextResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_protos_memory_service_proto protoreflect.FileDescriptor

const file_protos_memory_service_proto_rawDesc = "" +
	"\n" +
	"\x1bprotos/memory_service.proto\x12\x06memory\"\xbe\x01\n" +
	"\x12SaveContextRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12A\n" +
	"\acontext\x18\x02 \x03(\v2'.memory.SaveContextRequest.ContextEntryR\acontext\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x03R\x03ttl\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\x13SaveContextResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"@\n" +
	"\x11GetContextRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\tR\x04keys\"\xc3\x01\n" +
	"\x12GetContextResponse\x12A\n" +
	"\acontext\x18\x01 \x03(\v2'.memory.GetContextResponse.ContextEntryR\acontext\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x14DeleteContextRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\tR\x04keys\"G\n" +
	"\x15DeleteContextResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xc2\x01\n" +
	"\x14UpdateContextRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12C\n" +
	"\acontext\x18\x02 \x03(\v2).memory.UpdateContextRequest.ContextEntryR\acontext\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x03R\x03ttl\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\x15UpdateContextResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xb8\x02\n" +
	"\rMemoryService\x12F\n" +
	"\vSaveContext\x12\x1a.memory.SaveContextRequest\x1a\x1b.memory.SaveContextResponse\x12C\n" +
	"\n" +
	"GetContext\x12\x19.memory.GetContextRequest\x1a\x1a.memory.GetContextResponse\x12L\n" +
	"\rDeleteContext\x12\x1c.memory.DeleteContextRequest\x1a\x1d.memory.DeleteContextResponse\x12L\n" +
	"\rUpdateContext\x12\x1c.memory.UpdateContextRequest\x1a\x1d.memory.UpdateContextResponseB\tZ\a./protob\x06proto3"

var (
	file_protos_memory_service_proto_rawDescOnce sync.Once
	file_protos_memory_service_proto_rawDescData []byte
)

func file_protos_memory_service_proto_rawDescGZIP() []byte {
	file_protos_memory_service_proto_rawDescOnce.Do(func() {
		file_protos_memory_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_memory_service_proto_rawDesc), len(file_protos_memory_service_proto_rawDesc)))
	})
	return file_protos_memory_service_proto_rawDescData
}

var file_protos_memory_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_protos_memory_service_proto_goTypes = []any{
	(*SaveContextRequest)(nil),    // 0: memory.SaveContextRequest
	(*SaveContextResponse)(nil),   // 1: memory.SaveContextResponse
	(*GetContextRequest)(nil),     // 2: memory.GetContextRequest
	(*GetContextResponse)(nil),    // 3: memory.GetContextResponse
	(*DeleteContextRequest)(nil),  // 4: memory.DeleteContextRequest
	(*DeleteContextResponse)(nil), // 5: memory.DeleteContextResponse
	(*UpdateContextRequest)(nil),  // 6: memory.UpdateContextRequest
	(*UpdateContextResponse)(nil), // 7: memory.UpdateContextResponse
	nil,                           // 8: memory.SaveContextRequest.ContextEntry
	nil,                           // 9: memory.GetContextResponse.ContextEntry
	nil,                           // 10: memory.UpdateContextRequest.ContextEntry
}
var file_protos_memory_service_proto_depIdxs = []int32{
	8,  // 0: memory.SaveContextRequest.context:type_name -> memory.SaveContextRequest.ContextEntry
	9,  // 1: memory.GetContextResponse.context:type_name -> memory.GetContextResponse.ContextEntry
	10, // 2: memory.UpdateContextRequest.context:type_name -> memory.UpdateContextRequest.ContextEntry
	0,  // 3: memory.MemoryService.SaveContext:input_type -> memory.SaveContextRequest
	2,  // 4: memory.MemoryService.GetContext:input_type -> memory.GetContextRequest
	4,  // 5: memory.MemoryService.DeleteContext:input_type -> memory.DeleteContextRequest
	6,  // 6: memory.MemoryService.UpdateContext:input_type -> memory.UpdateContextRequest
	1,  // 7: memory.MemoryService.SaveContext:output_type -> memory.SaveContextResponse
	3,  // 8: memory.MemoryService.GetContext:output_type -> memory.GetContextResponse
	5,  // 9: memory.MemoryService.DeleteContext:output_type -> memory.DeleteContextResponse
	7,  // 10: memory.MemoryService.UpdateContext:output_type -> memory.UpdateContextResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_protos_memory_service_proto_init() }
func file_protos_memory_service_proto_init() {
	if File_protos_memory_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_memory_service_proto_rawDesc), len(file_protos_memory_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_memory_service_proto_goTypes,
		DependencyIndexes: file_protos_memory_service_proto_depIdxs,
		MessageInfos:      file_protos_memory_service_proto_msgTypes,
	}.Build()
	File_protos_memory_service_proto = out.File
	file_protos_memory_service_proto_goTypes = nil
	file_protos_memory_service_proto_depIdxs = nil
}
