// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: memory_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Context       map[string]string      `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ttl           int64                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"` // Time to live in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveContextRequest) Reset() {
	*x = SaveContextRequest{}
	mi := &file_memory_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveContextRequest) ProtoMessage() {}

func (x *SaveContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveContextRequest.ProtoReflect.Descriptor instead.
func (*SaveContextRequest) Descriptor() ([]byte, []int) {
	return file_memory_service_proto_rawDescGZIP(), []int{0}
}

func (x *SaveContextRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SaveContextRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *SaveContextRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type SaveContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveContextResponse) Reset() {
	*x = SaveContextResponse{}
	mi := &file_memory_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveContextResponse) ProtoMessage() {}

func (x *SaveContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveContextResponse.ProtoReflect.Descriptor instead.
func (*SaveContextResponse) Descriptor() ([]byte, []int) {
	return file_memory_service_proto_rawDescGZIP(), []int{1}
}

func (x *SaveContextResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveContextResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Keys          []string               `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"` // Optional: specific keys to retrieve
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContextRequest) Reset() {
	*x = GetContextRequest{}
	mi := &file_memory_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContextRequest) ProtoMessage() {}

func (x *GetContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContextRequest.ProtoReflect.Descriptor instead.
func (*GetContextRequest) Descriptor() ([]byte, []int) {
	return file_memory_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetContextRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetContextRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type GetContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       map[string]string      `protobuf:"bytes,1,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContextResponse) Reset() {
	*x = GetContextResponse{}
	mi := &file_memory_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContextResponse) ProtoMessage() {}

func (x *GetContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContextResponse.ProtoReflect.Descriptor instead.
func (*GetContextResponse) Descriptor() ([]byte, []int) {
	return file_memory_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetContextResponse) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetContextResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetContextResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Keys          []string               `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"` // Optional: specific keys to delete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContextRequest) Reset() {
	*x = DeleteContextRequest{}
	mi := &file_memory_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContextRequest) ProtoMessage() {}

func (x *DeleteContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContextRequest.ProtoReflect.Descriptor instead.
func (*DeleteContextRequest) Descriptor() ([]byte, []int) {
	return file_memory_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteContextRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteContextRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type DeleteContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContextResponse) Reset() {
	*x = DeleteContextResponse{}
	mi := &file_memory_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContextResponse) ProtoMessage() {}

func (x *DeleteContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContextResponse.ProtoReflect.Descriptor instead.
func (*DeleteContextResponse) Descriptor() ([]byte, []int) {
	return file_memory_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteContextResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteContextResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Context       map[string]string      `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ttl           int64                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"` // Optional: new TTL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContextRequest) Reset() {
	*x = UpdateContextRequest{}
	mi := &file_memory_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContextRequest) ProtoMessage() {}

func (x *UpdateContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContextRequest.ProtoReflect.Descriptor instead.
func (*UpdateContextRequest) Descriptor() ([]byte, []int) {
	return file_memory_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateContextRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateContextRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UpdateContextRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type UpdateContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContextResponse) Reset() {
	*x = UpdateContextResponse{}
	mi := &file_memory_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContextResponse) ProtoMessage() {}

func (x *UpdateContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContextResponse.ProtoReflect.Descriptor instead.
func (*UpdateContextResponse) Descriptor() ([]byte, []int) {
	return file_memory_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateContextResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateContextResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SaveVectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"` // Collection name
	Vectors       []*VectorData          `protobuf:"bytes,2,rep,name=vectors,proto3" json:"vectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveVectorRequest) Reset() {
	*x = SaveVectorRequest{}
	mi := &file_memory_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveVectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveVectorRequest) ProtoMessage() {}

func (x *SaveVectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveVectorRequest.ProtoReflect.Descriptor instead.
func (*SaveVectorRequest) Descriptor() ([]byte, []int) {
	return file_memory_service_proto_rawDescGZIP(), []int{8}
}

func (x *SaveVectorRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *SaveVectorRequest) GetVectors() []*VectorData {
	if x != nil {
		return x.Vectors
	}
	return nil
}

type VectorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                      // Unique vector ID
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`                                                                      // Embedding vector
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Associated metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorData) Reset() {
	*x = VectorData{}
	mi := &file_memory_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorData) ProtoMessage() {}

func (x *VectorData) ProtoReflect() protoreflect.Message {
	mi := &file_memory_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorData.ProtoReflect.Descriptor instead.
func (*VectorData) Descriptor() ([]byte, []int) {
	return file_memory_service_proto_rawDescGZIP(), []int{9}
}

func (x *VectorData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VectorData) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *VectorData) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SaveVectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	InsertedIds   []int64                `protobuf:"varint,3,rep,packed,name=inserted_ids,json=insertedIds,proto3" json:"inserted_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveVectorResponse) Reset() {
	*x = SaveVectorResponse{}
	mi := &file_memory_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveVectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveVectorResponse) ProtoMessage() {}

func (x *SaveVectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveVectorResponse.ProtoReflect.Descriptor instead.
func (*SaveVectorResponse) Descriptor() ([]byte, []int) {
	return file_memory_service_proto_rawDescGZIP(), []int{10}
}

func (x *SaveVectorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveVectorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SaveVectorResponse) GetInsertedIds() []int64 {
	if x != nil {
		return x.InsertedIds
	}
	return nil
}

type SearchSimilarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"` // Collection name
	QueryVector   []float32              `protobuf:"fixed32,2,rep,packed,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"`
	TopK          int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`                                                                  // Number of results
	Filter        map[string]string      `protobuf:"bytes,4,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Metadata filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSimilarRequest) Reset() {
	*x = SearchSimilarRequest{}
	mi := &file_memory_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSimilarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSimilarRequest) ProtoMessage() {}

func (x *SearchSimilarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSimilarRequest.ProtoReflect.Descriptor instead.
func (*SearchSimilarRequest) Descriptor() ([]byte, []int) {
	return file_memory_service_proto_rawDescGZIP(), []int{11}
}

func (x *SearchSimilarRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *SearchSimilarRequest) GetQueryVector() []float32 {
	if x != nil {
		return x.QueryVector
	}
	return nil
}

func (x *SearchSimilarRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchSimilarRequest) GetFilter() map[string]string {
	if x != nil {
		return x.Filter
	}
	return nil
}

type SearchSimilarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Results       []*SearchResult        `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSimilarResponse) Reset() {
	*x = SearchSimilarResponse{}
	mi := &file_memory_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSimilarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSimilarResponse) ProtoMessage() {}

func (x *SearchSimilarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSimilarResponse.ProtoReflect.Descriptor instead.
func (*SearchSimilarResponse) Descriptor() ([]byte, []int) {
	return file_memory_service_proto_rawDescGZIP(), []int{12}
}

func (x *SearchSimilarResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SearchSimilarResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SearchSimilarResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Score         float32                `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"` // Similarity score
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_memory_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_memory_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_memory_service_proto_rawDescGZIP(), []int{13}
}

func (x *SearchResult) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchResult) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *SearchResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type DeleteVectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Ids           []int64                `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVectorRequest) Reset() {
	*x = DeleteVectorRequest{}
	mi := &file_memory_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVectorRequest) ProtoMessage() {}

func (x *DeleteVectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVectorRequest.ProtoReflect.Descriptor instead.
func (*DeleteVectorRequest) Descriptor() ([]byte, []int) {
	return file_memory_service_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteVectorRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DeleteVectorRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteVectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVectorResponse) Reset() {
	*x = DeleteVectorResponse{}
	mi := &file_memory_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVectorResponse) ProtoMessage() {}

func (x *DeleteVectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVectorResponse.ProtoReflect.Descriptor instead.
func (*DeleteVectorResponse) Descriptor() ([]byte, []int) {
	return file_memory_service_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteVectorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteVectorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type KnowledgePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Mastery       float64                `protobuf:"fixed64,2,opt,name=mastery,proto3" json:"mastery,omitempty"`                     // 0-1 mastery level
	Interactions  int32                  `protobuf:"varint,3,opt,name=interactions,proto3" json:"interactions,omitempty"`            // Number of interactions
	LastSeen      int64                  `protobuf:"varint,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`    // Last seen timestamp
	FirstSeen     int64                  `protobuf:"varint,5,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"` // First seen timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgePoint) Reset() {
	*x = KnowledgePoint{}
	mi := &file_memory_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgePoint) ProtoMessage() {}

func (x *KnowledgePoint) ProtoReflect() protoreflect.Message {
	mi := &file_memory_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgePoint.ProtoReflect.Descriptor instead.
func (*KnowledgePoint) Descriptor() ([]byte, []int) {
	return file_memory_service_proto_rawDescGZIP(), []int{16}
}

func (x *KnowledgePoint) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *KnowledgePoint) GetMastery() float64 {
	if x != nil {
		return x.Mastery
	}
	return 0
}

func (x *KnowledgePoint) GetInteractions() int32 {
	if x != nil {
		return x.Interactions
	}
	return 0
}

func (x *KnowledgePoint) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *KnowledgePoint) GetFirstSeen() int64 {
	if x != nil {
		return x.FirstSeen
	}
	return 0
}

type SaveKnowledgePointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Point         *KnowledgePoint        `protobuf:"bytes,2,opt,name=point,proto3" json:"point,omitempty"`
	Merge         bool                   `protobuf:"varint,3,opt,name=merge,proto3" json:"merge,omitempty"` // true=merge into existing, false=overwrite
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveKnowledgePointRequest) Reset() {
	*x = SaveKnowledgePointRequest{}
	mi := &file_memory_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveKnowledgePointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveKnowledgePointRequest) ProtoMessage() {}

func (x *SaveKnowledgePointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveKnowledgePointRequest.ProtoReflect.Descriptor instead.
func (*SaveKnowledgePointRequest) Descriptor() ([]byte, []int) {
	return file_memory_service_proto_rawDescGZIP(), []int{17}
}

func (x *SaveKnowledgePointRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SaveKnowledgePointRequest) GetPoint() *KnowledgePoint {
	if x != nil {
		return x.Point
	}
	return nil
}

func (x *SaveKnowledgePointRequest) GetMerge() bool {
	if x != nil {
		return x.Merge
	}
	return false
}

type SaveKnowledgePointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"` // Final stored topic name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveKnowledgePointResponse) Reset() {
	*x = SaveKnowledgePointResponse{}
	mi := &file_memory_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveKnowledgePointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveKnowledgePointResponse) ProtoMessage() {}

func (x *SaveKnowledgePointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveKnowledgePointResponse.ProtoReflect.Descriptor instead.
func (*SaveKnowledgePointResponse) Descriptor() ([]byte, []int) {
	return file_memory_service_proto_rawDescGZIP(), []int{18}
}

func (x *SaveKnowledgePointResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveKnowledgePointResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SaveKnowledgePointResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type GetKnowledgePointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                // 0=return all
	SortBy        string                 `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"` // "mastery"/"interactions"/"last_seen"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnowledgePointsRequest) Reset() {
	*x = GetKnowledgePointsRequest{}
	mi := &file_memory_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnowledgePointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgePointsRequest) ProtoMessage() {}

func (x *GetKnowledgePointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgePointsRequest.ProtoReflect.Descriptor instead.
func (*GetKnowledgePointsRequest) Descriptor() ([]byte, []int) {
	return file_memory_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetKnowledgePointsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetKnowledgePointsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetKnowledgePointsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

type GetKnowledgePointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Points        []*KnowledgePoint      `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnowledgePointsResponse) Reset() {
	*x = GetKnowledgePointsResponse{}
	mi := &file_memory_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnowledgePointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgePointsResponse) ProtoMessage() {}

func (x *GetKnowledgePointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgePointsResponse.ProtoReflect.Descriptor instead.
func (*GetKnowledgePointsResponse) Descriptor() ([]byte, []int) {
	return file_memory_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetKnowledgePointsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetKnowledgePointsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetKnowledgePointsResponse) GetPoints() []*KnowledgePoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type GetLearningStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLearningStatsRequest) Reset() {
	*x = GetLearningStatsRequest{}
	mi := &file_memory_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLearningStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLearningStatsRequest) ProtoMessage() {}

func (x *GetLearningStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLearningStatsRequest.ProtoReflect.Descriptor instead.
func (*GetLearningStatsRequest) Descriptor() ([]byte, []int) {
	return file_memory_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetLearningStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetLearningStatsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error             string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	TotalTopics       int32                  `protobuf:"varint,3,opt,name=total_topics,json=totalTopics,proto3" json:"total_topics,omitempty"`
	AverageMastery    float64                `protobuf:"fixed64,4,opt,name=average_mastery,json=averageMastery,proto3" json:"average_mastery,omitempty"`
	TotalInteractions int32                  `protobuf:"varint,5,opt,name=total_interactions,json=totalInteractions,proto3" json:"total_interactions,omitempty"`
	MasteredCount     int32                  `protobuf:"varint,6,opt,name=mastered_count,json=masteredCount,proto3" json:"mastered_count,omitempty"` // mastery >= 0.8
	LearningCount     int32                  `protobuf:"varint,7,opt,name=learning_count,json=learningCount,proto3" json:"learning_count,omitempty"` // 0.3 <= mastery < 0.8
	WeakCount         int32                  `protobuf:"varint,8,opt,name=weak_count,json=weakCount,proto3" json:"weak_count,omitempty"`             // mastery < 0.3
	StudyStartDate    int64                  `protobuf:"varint,9,opt,name=study_start_date,json=studyStartDate,proto3" json:"study_start_date,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetLearningStatsResponse) Reset() {
	*x = GetLearningStatsResponse{}
	mi := &file_memory_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLearningStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLearningStatsResponse) ProtoMessage() {}

func (x *GetLearningStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLearningStatsResponse.ProtoReflect.Descriptor instead.
func (*GetLearningStatsResponse) Descriptor() ([]byte, []int) {
	return file_memory_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetLearningStatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetLearningStatsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetLearningStatsResponse) GetTotalTopics() int32 {
	if x != nil {
		return x.TotalTopics
	}
	return 0
}

func (x *GetLearningStatsResponse) GetAverageMastery() float64 {
	if x != nil {
		return x.AverageMastery
	}
	return 0
}

func (x *GetLearningStatsResponse) GetTotalInteractions() int32 {
	if x != nil {
		return x.TotalInteractions
	}
	return 0
}

func (x *GetLearningStatsResponse) GetMasteredCount() int32 {
	if x != nil {
		return x.MasteredCount
	}
	return 0
}

func (x *GetLearningStatsResponse) GetLearningCount() int32 {
	if x != nil {
		return x.LearningCount
	}
	return 0
}

func (x *GetLearningStatsResponse) GetWeakCount() int32 {
	if x != nil {
		return x.WeakCount
	}
	return 0
}

func (x *GetLearningStatsResponse) GetStudyStartDate() int64 {
	if x != nil {
		return x.StudyStartDate
	}
	return 0
}

var File_memory_service_proto protoreflect.FileDescriptor

const file_memory_service_proto_rawDesc = "" +
	"\n" +
	"\x14memory_service.proto\x12\x06memory\"\xbe\x01\n" +
	"\x12SaveContextRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12A\n" +
	"\acontext\x18\x02 \x03(\v2'.memory.SaveContextRequest.ContextEntryR\acontext\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x03R\x03ttl\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\x13SaveContextResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"@\n" +
	"\x11GetContextRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\tR\x04keys\"\xc3\x01\n" +
	"\x12GetContextResponse\x12A\n" +
	"\acontext\x18\x01 \x03(\v2'.memory.GetContextResponse.ContextEntryR\acontext\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x14DeleteContextRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\tR\x04keys\"G\n" +
	"\x15DeleteContextResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xc2\x01\n" +
	"\x14UpdateContextRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12C\n" +
	"\acontext\x18\x02 \x03(\v2).memory.UpdateContextRequest.ContextEntryR\acontext\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x03R\x03ttl\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\x15UpdateContextResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"a\n" +
	"\x11SaveVectorRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12,\n" +
	"\avectors\x18\x02 \x03(\v2\x12.memory.VectorDataR\avectors\"\xaf\x01\n" +
	"\n" +
	"VectorData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\x12<\n" +
	"\bmetadata\x18\x03 \x03(\v2 .memory.VectorData.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"g\n" +
	"\x12SaveVectorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12!\n" +
	"\finserted_ids\x18\x03 \x03(\x03R\vinsertedIds\"\xeb\x01\n" +
	"\x14SearchSimilarRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12!\n" +
	"\fquery_vector\x18\x02 \x03(\x02R\vqueryVector\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\x12@\n" +
	"\x06filter\x18\x04 \x03(\v2(.memory.SearchSimilarRequest.FilterEntryR\x06filter\x1a9\n" +
	"\vFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"w\n" +
	"\x15SearchSimilarResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12.\n" +
	"\aresults\x18\x03 \x03(\v2\x14.memory.SearchResultR\aresults\"\xc9\x01\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\x12>\n" +
	"\bmetadata\x18\x03 \x03(\v2\".memory.SearchResult.MetadataEntryR\bmetadata\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x02R\x05score\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\x13DeleteVectorRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\x03R\x03ids\"F\n" +
	"\x14DeleteVectorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa0\x01\n" +
	"\x0eKnowledgePoint\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\amastery\x18\x02 \x01(\x01R\amastery\x12\"\n" +
	"\finteractions\x18\x03 \x01(\x05R\finteractions\x12\x1b\n" +
	"\tlast_seen\x18\x04 \x01(\x03R\blastSeen\x12\x1d\n" +
	"\n" +
	"first_seen\x18\x05 \x01(\x03R\tfirstSeen\"x\n" +
	"\x19SaveKnowledgePointRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12,\n" +
	"\x05point\x18\x02 \x01(\v2\x16.memory.KnowledgePointR\x05point\x12\x14\n" +
	"\x05merge\x18\x03 \x01(\bR\x05merge\"b\n" +
	"\x1aSaveKnowledgePointResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\"c\n" +
	"\x19GetKnowledgePointsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\"|\n" +
	"\x1aGetKnowledgePointsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12.\n" +
	"\x06points\x18\x03 \x03(\v2\x16.memory.KnowledgePointR\x06points\"2\n" +
	"\x17GetLearningStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xdc\x02\n" +
	"\x18GetLearningStatsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12!\n" +
	"\ftotal_topics\x18\x03 \x01(\x05R\vtotalTopics\x12'\n" +
	"\x0faverage_mastery\x18\x04 \x01(\x01R\x0eaverageMastery\x12-\n" +
	"\x12total_interactions\x18\x05 \x01(\x05R\x11totalInteractions\x12%\n" +
	"\x0emastered_count\x18\x06 \x01(\x05R\rmasteredCount\x12%\n" +
	"\x0elearning_count\x18\a \x01(\x05R\rlearningCount\x12\x1d\n" +
	"\n" +
	"weak_count\x18\b \x01(\x05R\tweakCount\x12(\n" +
	"\x10study_start_date\x18\t \x01(\x03R\x0estudyStartDate2\xa7\x06\n" +
	"\rMemoryService\x12F\n" +
	"\vSaveContext\x12\x1a.memory.SaveContextRequest\x1a\x1b.memory.SaveContextResponse\x12C\n" +
	"\n" +
	"GetContext\x12\x19.memory.GetContextRequest\x1a\x1a.memory.GetContextResponse\x12L\n" +
	"\rDeleteContext\x12\x1c.memory.DeleteContextRequest\x1a\x1d.memory.DeleteContextResponse\x12L\n" +
	"\rUpdateContext\x12\x1c.memory.UpdateContextRequest\x1a\x1d.memory.UpdateContextResponse\x12C\n" +
	"\n" +
	"SaveVector\x12\x19.memory.SaveVectorRequest\x1a\x1a.memory.SaveVectorResponse\x12L\n" +
	"\rSearchSimilar\x12\x1c.memory.SearchSimilarRequest\x1a\x1d.memory.SearchSimilarResponse\x12I\n" +
	"\fDeleteVector\x12\x1b.memory.DeleteVectorRequest\x1a\x1c.memory.DeleteVectorResponse\x12[\n" +
	"\x12SaveKnowledgePoint\x12!.memory.SaveKnowledgePointRequest\x1a\".memory.SaveKnowledgePointResponse\x12[\n" +
	"\x12GetKnowledgePoints\x12!.memory.GetKnowledgePointsRequest\x1a\".memory.GetKnowledgePointsResponse\x12U\n" +
	"\x10GetLearningStats\x12\x1f.memory.GetLearningStatsRequest\x1a .memory.GetLearningStatsResponseB\tZ\a./protob\x06proto3"

var (
	file_memory_service_proto_rawDescOnce sync.Once
	file_memory_service_proto_rawDescData []byte
)

func file_memory_service_proto_rawDescGZIP() []byte {
	file_memory_service_proto_rawDescOnce.Do(func() {
		file_memory_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_memory_service_proto_rawDesc), len(file_memory_service_proto_rawDesc)))
	})
	return file_memory_service_proto_rawDescData
}

var file_memory_service_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_memory_service_proto_goTypes = []any{
	(*SaveContextRequest)(nil),         // 0: memory.SaveContextRequest
	(*SaveContextResponse)(nil),        // 1: memory.SaveContextResponse
	(*GetContextRequest)(nil),          // 2: memory.GetContextRequest
	(*GetContextResponse)(nil),         // 3: memory.GetContextResponse
	(*DeleteContextRequest)(nil),       // 4: memory.DeleteContextRequest
	(*DeleteContextResponse)(nil),      // 5: memory.DeleteContextResponse
	(*UpdateContextRequest)(nil),       // 6: memory.UpdateContextRequest
	(*UpdateContextResponse)(nil),      // 7: memory.UpdateContextResponse
	(*SaveVectorRequest)(nil),          // 8: memory.SaveVectorRequest
	(*VectorData)(nil),                 // 9: memory.VectorData
	(*SaveVectorResponse)(nil),         // 10: memory.SaveVectorResponse
	(*SearchSimilarRequest)(nil),       // 11: memory.SearchSimilarRequest
	(*SearchSimilarResponse)(nil),      // 12: memory.SearchSimilarResponse
	(*SearchResult)(nil),               // 13: memory.SearchResult
	(*DeleteVectorRequest)(nil),        // 14: memory.DeleteVectorRequest
	(*DeleteVectorResponse)(nil),       // 15: memory.DeleteVectorResponse
	(*KnowledgePoint)(nil),             // 16: memory.KnowledgePoint
	(*SaveKnowledgePointRequest)(nil),  // 17: memory.SaveKnowledgePointRequest
	(*SaveKnowledgePointResponse)(nil), // 18: memory.SaveKnowledgePointResponse
	(*GetKnowledgePointsRequest)(nil),  // 19: memory.GetKnowledgePointsRequest
	(*GetKnowledgePointsResponse)(nil), // 20: memory.GetKnowledgePointsResponse
	(*GetLearningStatsRequest)(nil),    // 21: memory.GetLearningStatsRequest
	(*GetLearningStatsResponse)(nil),   // 22: memory.GetLearningStatsResponse
	nil,                                // 23: memory.SaveContextRequest.ContextEntry
	nil,                                // 24: memory.GetContextResponse.ContextEntry
	nil,                                // 25: memory.UpdateContextRequest.ContextEntry
	nil,                                // 26: memory.VectorData.MetadataEntry
	nil,                                // 27: memory.SearchSimilarRequest.FilterEntry
	nil,                                // 28: memory.SearchResult.MetadataEntry
}
var file_memory_service_proto_depIdxs = []int32{
	23, // 0: memory.SaveContextRequest.context:type_name -> memory.SaveContextRequest.ContextEntry
	24, // 1: memory.GetContextResponse.context:type_name -> memory.GetContextResponse.ContextEntry
	25, // 2: memory.UpdateContextRequest.context:type_name -> memory.UpdateContextRequest.ContextEntry
	9,  // 3: memory.SaveVectorRequest.vectors:type_name -> memory.VectorData
	26, // 4: memory.VectorData.metadata:type_name -> memory.VectorData.MetadataEntry
	27, // 5: memory.SearchSimilarRequest.filter:type_name -> memory.SearchSimilarRequest.FilterEntry
	13, // 6: memory.SearchSimilarResponse.results:type_name -> memory.SearchResult
	28, // 7: memory.SearchResult.metadata:type_name -> memory.SearchResult.MetadataEntry
	16, // 8: memory.SaveKnowledgePointRequest.point:type_name -> memory.KnowledgePoint
	16, // 9: memory.GetKnowledgePointsResponse.points:type_name -> memory.KnowledgePoint
	0,  // 10: memory.MemoryService.SaveContext:input_type -> memory.SaveContextRequest
	2,  // 11: memory.MemoryService.GetContext:input_type -> memory.GetContextRequest
	4,  // 12: memory.MemoryService.DeleteContext:input_type -> memory.DeleteContextRequest
	6,  // 13: memory.MemoryService.UpdateContext:input_type -> memory.UpdateContextRequest
	8,  // 14: memory.MemoryService.SaveVector:input_type -> memory.SaveVectorRequest
	11, // 15: memory.MemoryService.SearchSimilar:input_type -> memory.SearchSimilarRequest
	14, // 16: memory.MemoryService.DeleteVector:input_type -> memory.DeleteVectorRequest
	17, // 17: memory.MemoryService.SaveKnowledgePoint:input_type -> memory.SaveKnowledgePointRequest
	19, // 18: memory.MemoryService.GetKnowledgePoints:input_type -> memory.GetKnowledgePointsRequest
	21, // 19: memory.MemoryService.GetLearningStats:input_type -> memory.GetLearningStatsRequest
	1,  // 20: memory.MemoryService.SaveContext:output_type -> memory.SaveContextResponse
	3,  // 21: memory.MemoryService.GetContext:output_type -> memory.GetContextResponse
	5,  // 22: memory.MemoryService.DeleteContext:output_type -> memory.DeleteContextResponse
	7,  // 23: memory.MemoryService.UpdateContext:output_type -> memory.UpdateContextResponse
	10, // 24: memory.MemoryService.SaveVector:output_type -> memory.SaveVectorResponse
	12, // 25: memory.MemoryService.SearchSimilar:output_type -> memory.SearchSimilarResponse
	15, // 26: memory.MemoryService.DeleteVector:output_type -> memory.DeleteVectorResponse
	18, // 27: memory.MemoryService.SaveKnowledgePoint:output_type -> memory.SaveKnowledgePointResponse
	20, // 28: memory.MemoryService.GetKnowledgePoints:output_type -> memory.GetKnowledgePointsResponse
	22, // 29: memory.MemoryService.GetLearningStats:output_type -> memory.GetLearningStatsResponse
	20, // [20:30] is the sub-list for method output_type
	10, // [10:20] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_memory_service_proto_init() }
func file_memory_service_proto_init() {
	if File_memory_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_memory_service_proto_rawDesc), len(file_memory_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_memory_service_proto_goTypes,
		DependencyIndexes: file_memory_service_proto_depIdxs,
		MessageInfos:      file_memory_service_proto_msgTypes,
	}.Build()
	File_memory_service_proto = out.File
	file_memory_service_proto_goTypes = nil
	file_memory_service_proto_depIdxs = nil
}
