// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: memory_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MemoryService_SaveContext_FullMethodName        = "/memory.MemoryService/SaveContext"
	MemoryService_GetContext_FullMethodName         = "/memory.MemoryService/GetContext"
	MemoryService_DeleteContext_FullMethodName      = "/memory.MemoryService/DeleteContext"
	MemoryService_UpdateContext_FullMethodName      = "/memory.MemoryService/UpdateContext"
	MemoryService_SaveVector_FullMethodName         = "/memory.MemoryService/SaveVector"
	MemoryService_SearchSimilar_FullMethodName      = "/memory.MemoryService/SearchSimilar"
	MemoryService_DeleteVector_FullMethodName       = "/memory.MemoryService/DeleteVector"
	MemoryService_SaveKnowledgePoint_FullMethodName = "/memory.MemoryService/SaveKnowledgePoint"
	MemoryService_GetKnowledgePoints_FullMethodName = "/memory.MemoryService/GetKnowledgePoints"
	MemoryService_GetLearningStats_FullMethodName   = "/memory.MemoryService/GetLearningStats"
)

// MemoryServiceClient is the client API for MemoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MemoryServiceClient interface {
	// Key-value context (Redis)
	SaveContext(ctx context.Context, in *SaveContextRequest, opts ...grpc.CallOption) (*SaveContextResponse, error)
	GetContext(ctx context.Context, in *GetContextRequest, opts ...grpc.CallOption) (*GetContextResponse, error)
	DeleteContext(ctx context.Context, in *DeleteContextRequest, opts ...grpc.CallOption) (*DeleteContextResponse, error)
	UpdateContext(ctx context.Context, in *UpdateContextRequest, opts ...grpc.CallOption) (*UpdateContextResponse, error)
	// Vector operations (Milvus)
	SaveVector(ctx context.Context, in *SaveVectorRequest, opts ...grpc.CallOption) (*SaveVectorResponse, error)
	SearchSimilar(ctx context.Context, in *SearchSimilarRequest, opts ...grpc.CallOption) (*SearchSimilarResponse, error)
	DeleteVector(ctx context.Context, in *DeleteVectorRequest, opts ...grpc.CallOption) (*DeleteVectorResponse, error)
	// Knowledge point tracking
	SaveKnowledgePoint(ctx context.Context, in *SaveKnowledgePointRequest, opts ...grpc.CallOption) (*SaveKnowledgePointResponse, error)
	GetKnowledgePoints(ctx context.Context, in *GetKnowledgePointsRequest, opts ...grpc.CallOption) (*GetKnowledgePointsResponse, error)
	GetLearningStats(ctx context.Context, in *GetLearningStatsRequest, opts ...grpc.CallOption) (*GetLearningStatsResponse, error)
}

type memoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMemoryServiceClient(cc grpc.ClientConnInterface) MemoryServiceClient {
	return &memoryServiceClient{cc}
}

func (c *memoryServiceClient) SaveContext(ctx context.Context, in *SaveContextRequest, opts ...grpc.CallOption) (*SaveContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveContextResponse)
	err := c.cc.Invoke(ctx, MemoryService_SaveContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) GetContext(ctx context.Context, in *GetContextRequest, opts ...grpc.CallOption) (*GetContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContextResponse)
	err := c.cc.Invoke(ctx, MemoryService_GetContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) DeleteContext(ctx context.Context, in *DeleteContextRequest, opts ...grpc.CallOption) (*DeleteContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteContextResponse)
	err := c.cc.Invoke(ctx, MemoryService_DeleteContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) UpdateContext(ctx context.Context, in *UpdateContextRequest, opts ...grpc.CallOption) (*UpdateContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateContextResponse)
	err := c.cc.Invoke(ctx, MemoryService_UpdateContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) SaveVector(ctx context.Context, in *SaveVectorRequest, opts ...grpc.CallOption) (*SaveVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveVectorResponse)
	err := c.cc.Invoke(ctx, MemoryService_SaveVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) SearchSimilar(ctx context.Context, in *SearchSimilarRequest, opts ...grpc.CallOption) (*SearchSimilarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchSimilarResponse)
	err := c.cc.Invoke(ctx, MemoryService_SearchSimilar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) DeleteVector(ctx context.Context, in *DeleteVectorRequest, opts ...grpc.CallOption) (*DeleteVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVectorResponse)
	err := c.cc.Invoke(ctx, MemoryService_DeleteVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) SaveKnowledgePoint(ctx context.Context, in *SaveKnowledgePointRequest, opts ...grpc.CallOption) (*SaveKnowledgePointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveKnowledgePointResponse)
	err := c.cc.Invoke(ctx, MemoryService_SaveKnowledgePoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) GetKnowledgePoints(ctx context.Context, in *GetKnowledgePointsRequest, opts ...grpc.CallOption) (*GetKnowledgePointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKnowledgePointsResponse)
	err := c.cc.Invoke(ctx, MemoryService_GetKnowledgePoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) GetLearningStats(ctx context.Context, in *GetLearningStatsRequest, opts ...grpc.CallOption) (*GetLearningStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLearningStatsResponse)
	err := c.cc.Invoke(ctx, MemoryService_GetLearningStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemoryServiceServer is the server API for MemoryService service.
// All implementations must embed UnimplementedMemoryServiceServer
// for forward compatibility.
type MemoryServiceServer interface {
	// Key-value context (Redis)
	SaveContext(context.Context, *SaveContextRequest) (*SaveContextResponse, error)
	GetContext(context.Context, *GetContextRequest) (*GetContextResponse, error)
	DeleteContext(context.Context, *DeleteContextRequest) (*DeleteContextResponse, error)
	UpdateContext(context.Context, *UpdateContextRequest) (*UpdateContextResponse, error)
	// Vector operations (Milvus)
	SaveVector(context.Context, *SaveVectorRequest) (*SaveVectorResponse, error)
	SearchSimilar(context.Context, *SearchSimilarRequest) (*SearchSimilarResponse, error)
	DeleteVector(context.Context, *DeleteVectorRequest) (*DeleteVectorResponse, error)
	// Knowledge point tracking
	SaveKnowledgePoint(context.Context, *SaveKnowledgePointRequest) (*SaveKnowledgePointResponse, error)
	GetKnowledgePoints(context.Context, *GetKnowledgePointsRequest) (*GetKnowledgePointsResponse, error)
	GetLearningStats(context.Context, *GetLearningStatsRequest) (*GetLearningStatsResponse, error)
	mustEmbedUnimplementedMemoryServiceServer()
}

// UnimplementedMemoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMemoryServiceServer struct{}

func (UnimplementedMemoryServiceServer) SaveContext(context.Context, *SaveContextRequest) (*SaveContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveContext not implemented")
}
func (UnimplementedMemoryServiceServer) GetContext(context.Context, *GetContextRequest) (*GetContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContext not implemented")
}
func (UnimplementedMemoryServiceServer) DeleteContext(context.Context, *DeleteContextRequest) (*DeleteContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteContext not implemented")
}
func (UnimplementedMemoryServiceServer) UpdateContext(context.Context, *UpdateContextRequest) (*UpdateContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateContext not implemented")
}
func (UnimplementedMemoryServiceServer) SaveVector(context.Context, *SaveVectorRequest) (*SaveVectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveVector not implemented")
}
func (UnimplementedMemoryServiceServer) SearchSimilar(context.Context, *SearchSimilarRequest) (*SearchSimilarResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchSimilar not implemented")
}
func (UnimplementedMemoryServiceServer) DeleteVector(context.Context, *DeleteVectorRequest) (*DeleteVectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVector not implemented")
}
func (UnimplementedMemoryServiceServer) SaveKnowledgePoint(context.Context, *SaveKnowledgePointRequest) (*SaveKnowledgePointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveKnowledgePoint not implemented")
}
func (UnimplementedMemoryServiceServer) GetKnowledgePoints(context.Context, *GetKnowledgePointsRequest) (*GetKnowledgePointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKnowledgePoints not implemented")
}
func (UnimplementedMemoryServiceServer) GetLearningStats(context.Context, *GetLearningStatsRequest) (*GetLearningStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLearningStats not implemented")
}
func (UnimplementedMemoryServiceServer) mustEmbedUnimplementedMemoryServiceServer() {}
func (UnimplementedMemoryServiceServer) testEmbeddedByValue()                       {}

// UnsafeMemoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemoryServiceServer will
// result in compilation errors.
type UnsafeMemoryServiceServer interface {
	mustEmbedUnimplementedMemoryServiceServer()
}

func RegisterMemoryServiceServer(s grpc.ServiceRegistrar, srv MemoryServiceServer) {
	// If the following call panics, it indicates UnimplementedMemoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MemoryService_ServiceDesc, srv)
}

func _MemoryService_SaveContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).SaveContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_SaveContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).SaveContext(ctx, req.(*SaveContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_GetContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).GetContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_GetContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).GetContext(ctx, req.(*GetContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_DeleteContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).DeleteContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_DeleteContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).DeleteContext(ctx, req.(*DeleteContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_UpdateContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).UpdateContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_UpdateContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).UpdateContext(ctx, req.(*UpdateContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_SaveVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).SaveVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_SaveVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).SaveVector(ctx, req.(*SaveVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_SearchSimilar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSimilarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).SearchSimilar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_SearchSimilar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).SearchSimilar(ctx, req.(*SearchSimilarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_DeleteVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).DeleteVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_DeleteVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).DeleteVector(ctx, req.(*DeleteVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_SaveKnowledgePoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveKnowledgePointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).SaveKnowledgePoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_SaveKnowledgePoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).SaveKnowledgePoint(ctx, req.(*SaveKnowledgePointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_GetKnowledgePoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKnowledgePointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).GetKnowledgePoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_GetKnowledgePoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).GetKnowledgePoints(ctx, req.(*GetKnowledgePointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_GetLearningStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLearningStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).GetLearningStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_GetLearningStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).GetLearningStats(ctx, req.(*GetLearningStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MemoryService_ServiceDesc is the grpc.ServiceDesc for MemoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MemoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "memory.MemoryService",
	HandlerType: (*MemoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveContext",
			Handler:    _MemoryService_SaveContext_Handler,
		},
		{
			MethodName: "GetContext",
			Handler:    _MemoryService_GetContext_Handler,
		},
		{
			MethodName: "DeleteContext",
			Handler:    _MemoryService_DeleteContext_Handler,
		},
		{
			MethodName: "UpdateContext",
			Handler:    _MemoryService_UpdateContext_Handler,
		},
		{
			MethodName: "SaveVector",
			Handler:    _MemoryService_SaveVector_Handler,
		},
		{
			MethodName: "SearchSimilar",
			Handler:    _MemoryService_SearchSimilar_Handler,
		},
		{
			MethodName: "DeleteVector",
			Handler:    _MemoryService_DeleteVector_Handler,
		},
		{
			MethodName: "SaveKnowledgePoint",
			Handler:    _MemoryService_SaveKnowledgePoint_Handler,
		},
		{
			MethodName: "GetKnowledgePoints",
			Handler:    _MemoryService_GetKnowledgePoints_Handler,
		},
		{
			MethodName: "GetLearningStats",
			Handler:    _MemoryService_GetLearningStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "memory_service.proto",
}
