// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: app/tool/tool.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ToolService_AnalyzeCodeError_FullMethodName        = "/tool.ToolService/AnalyzeCodeError"
	ToolService_QuerySyntax_FullMethodName             = "/tool.ToolService/QuerySyntax"
	ToolService_GenerateProblemSolution_FullMethodName = "/tool.ToolService/GenerateProblemSolution"
)

// ToolServiceClient is the client API for ToolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ToolServiceClient interface {
	AnalyzeCodeError(ctx context.Context, in *AnalyzeCodeErrorRequest, opts ...grpc.CallOption) (*AnalyzeCodeErrorResponse, error)
	QuerySyntax(ctx context.Context, in *QuerySyntaxRequest, opts ...grpc.CallOption) (*QuerySyntaxResponse, error)
	GenerateProblemSolution(ctx context.Context, in *GenerateProblemSolutionRequest, opts ...grpc.CallOption) (*GenerateProblemSolutionResponse, error)
}

type toolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewToolServiceClient(cc grpc.ClientConnInterface) ToolServiceClient {
	return &toolServiceClient{cc}
}

func (c *toolServiceClient) AnalyzeCodeError(ctx context.Context, in *AnalyzeCodeErrorRequest, opts ...grpc.CallOption) (*AnalyzeCodeErrorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeCodeErrorResponse)
	err := c.cc.Invoke(ctx, ToolService_AnalyzeCodeError_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) QuerySyntax(ctx context.Context, in *QuerySyntaxRequest, opts ...grpc.CallOption) (*QuerySyntaxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuerySyntaxResponse)
	err := c.cc.Invoke(ctx, ToolService_QuerySyntax_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) GenerateProblemSolution(ctx context.Context, in *GenerateProblemSolutionRequest, opts ...grpc.CallOption) (*GenerateProblemSolutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateProblemSolutionResponse)
	err := c.cc.Invoke(ctx, ToolService_GenerateProblemSolution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToolServiceServer is the server API for ToolService service.
// All implementations must embed UnimplementedToolServiceServer
// for forward compatibility.
type ToolServiceServer interface {
	AnalyzeCodeError(context.Context, *AnalyzeCodeErrorRequest) (*AnalyzeCodeErrorResponse, error)
	QuerySyntax(context.Context, *QuerySyntaxRequest) (*QuerySyntaxResponse, error)
	GenerateProblemSolution(context.Context, *GenerateProblemSolutionRequest) (*GenerateProblemSolutionResponse, error)
	mustEmbedUnimplementedToolServiceServer()
}

// UnimplementedToolServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToolServiceServer struct{}

func (UnimplementedToolServiceServer) AnalyzeCodeError(context.Context, *AnalyzeCodeErrorRequest) (*AnalyzeCodeErrorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeCodeError not implemented")
}
func (UnimplementedToolServiceServer) QuerySyntax(context.Context, *QuerySyntaxRequest) (*QuerySyntaxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QuerySyntax not implemented")
}
func (UnimplementedToolServiceServer) GenerateProblemSolution(context.Context, *GenerateProblemSolutionRequest) (*GenerateProblemSolutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateProblemSolution not implemented")
}
func (UnimplementedToolServiceServer) mustEmbedUnimplementedToolServiceServer() {}
func (UnimplementedToolServiceServer) testEmbeddedByValue()                     {}

// UnsafeToolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToolServiceServer will
// result in compilation errors.
type UnsafeToolServiceServer interface {
	mustEmbedUnimplementedToolServiceServer()
}

func RegisterToolServiceServer(s grpc.ServiceRegistrar, srv ToolServiceServer) {
	// If the following call panics, it indicates UnimplementedToolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ToolService_ServiceDesc, srv)
}

func _ToolService_AnalyzeCodeError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeCodeErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).AnalyzeCodeError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_AnalyzeCodeError_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).AnalyzeCodeError(ctx, req.(*AnalyzeCodeErrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_QuerySyntax_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySyntaxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).QuerySyntax(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_QuerySyntax_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).QuerySyntax(ctx, req.(*QuerySyntaxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_GenerateProblemSolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateProblemSolutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).GenerateProblemSolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_GenerateProblemSolution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).GenerateProblemSolution(ctx, req.(*GenerateProblemSolutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ToolService_ServiceDesc is the grpc.ServiceDesc for ToolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tool.ToolService",
	HandlerType: (*ToolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeCodeError",
			Handler:    _ToolService_AnalyzeCodeError_Handler,
		},
		{
			MethodName: "QuerySyntax",
			Handler:    _ToolService_QuerySyntax_Handler,
		},
		{
			MethodName: "GenerateProblemSolution",
			Handler:    _ToolService_GenerateProblemSolution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/tool/tool.proto",
}
